#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────
#
# WHAT: creates a dedicated, empty Langfuse Cloud project for the integration
#       tests and stores its keys locally (.env.integration, gitignored) and as
#       GitHub Actions secrets LANGFUSE_TEST_PUBLIC_KEY / _SECRET_KEY / _BASE_URL.
# WHY:  .claude/rules/testing.md — weekly + manual-dispatch Cloud integration run.
# WHEN: once, before the first Cloud integration workflow (M1); re-run to rotate keys.
# HOW:  ./scripts/setup-ci-langfuse-cloud.sh from anywhere inside the repo.

cd "$(git rev-parse --show-toplevel)"
ENV_FILE=".env.integration"

TOTAL_STAGES=5

banner "Langfuse Cloud test project for CI"

stage "Pick the Cloud region and sign in"
say "Use a region where you have (or can create) a free Hobby organization."
note "EU https://cloud.langfuse.com · US https://us.cloud.langfuse.com"
note "JP https://jp.cloud.langfuse.com · HIPAA https://hipaa.cloud.langfuse.com"
ask LANGFUSE_TEST_BASE_URL "Region base URL (Enter for EU):"
LANGFUSE_TEST_BASE_URL="${LANGFUSE_TEST_BASE_URL:-https://cloud.langfuse.com}"
LANGFUSE_TEST_BASE_URL="${LANGFUSE_TEST_BASE_URL%/}"
case "$LANGFUSE_TEST_BASE_URL" in https://*) ;; *) warn "must start with https:// — re-run the wizard"; exit 1;; esac
open_url "$LANGFUSE_TEST_BASE_URL"
step "Sign in (or sign up) and open the organization that will own the test project."
pause "Signed in? Press Enter"

stage "Create a dedicated, empty project"
warn "Never reuse a project with real data: tests create and delete objects in it."
step "In the organization, create a new project named: langfuse-api-mcp-ci"
note "(Look for 'New project' in the organization's project list or settings.)"
pause "Project created and open? Press Enter"

stage "Create project API keys"
step "Open the project's Settings → API Keys → create new API keys."
note "If the menu wording differs, find 'API Keys' under the project settings."
note "The secret key is typically shown only once — copy it now."
ask LANGFUSE_TEST_PUBLIC_KEY "Paste the public key (pk-lf-…):"
ask_secret LANGFUSE_TEST_SECRET_KEY "Paste the secret key (sk-lf-…, hidden):"
[[ "$LANGFUSE_TEST_PUBLIC_KEY" == pk-lf-* ]] || { warn "public key must start with pk-lf- — re-run"; exit 1; }
[[ "$LANGFUSE_TEST_SECRET_KEY" == sk-lf-* ]] || { warn "secret key must start with sk-lf- — re-run"; exit 1; }

stage "Check the keys against the API (read-only)"
say "Calling GET $LANGFUSE_TEST_BASE_URL/api/public/projects with the new keys…"
# ponytail: credentials go through curl's stdin config, never argv (hidden from ps).
status=$(printf 'user = "%s:%s"\n' "$LANGFUSE_TEST_PUBLIC_KEY" "$LANGFUSE_TEST_SECRET_KEY" \
  | curl -sS -o /dev/null -w '%{http_code}' -K - "$LANGFUSE_TEST_BASE_URL/api/public/projects" || echo "000")
case "$status" in
  200) printf '  %s✓ keys work%s (HTTP 200)\n' "$GREEN" "$RESET" ;;
  401) warn "HTTP 401 — wrong key pair or keys from another region."; confirm "Save anyway?" || exit 1 ;;
  000) warn "no response — network/TLS problem (corporate CA? proxy?)."; confirm "Save anyway?" || exit 1 ;;
  *)   warn "unexpected HTTP $status."; confirm "Save anyway?" || exit 1 ;;
esac
pause "Press Enter"

stage "Store the values (local file + GitHub secrets)"
say "Local: $ENV_FILE (gitignored). CI: GitHub Actions secrets of this repo."
write_env LANGFUSE_TEST_BASE_URL "$LANGFUSE_TEST_BASE_URL"
write_env LANGFUSE_TEST_PUBLIC_KEY "$LANGFUSE_TEST_PUBLIC_KEY"
write_env LANGFUSE_TEST_SECRET_KEY "$LANGFUSE_TEST_SECRET_KEY"
chmod 600 "$ENV_FILE"
if confirm "Write the 3 GitHub secrets to $(gh repo view --json nameWithOwner -q .nameWithOwner 2>/dev/null || echo 'this repo') now?"; then
  set_secret LANGFUSE_TEST_BASE_URL "$LANGFUSE_TEST_BASE_URL"
  set_secret LANGFUSE_TEST_PUBLIC_KEY "$LANGFUSE_TEST_PUBLIC_KEY"
  set_secret LANGFUSE_TEST_SECRET_KEY "$LANGFUSE_TEST_SECRET_KEY"
else
  SKIPPED+=("GitHub secrets LANGFUSE_TEST_* (re-run this wizard)")
fi
pause "Press Enter for the summary"

finish
